version: '3.8'

services:
  backend:
    build: .
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 7000 --reload

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend 