version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - CONTENT_SAFETY_ENDPOINT=${CONTENT_SAFETY_ENDPOINT}
      - CONTENT_SAFETY_KEY=${CONTENT_SAFETY_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 7000 --reload

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend 