services:
  - type: web
    name: content-safety-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false  
      - key: CONTENT_SAFETY_ENDPOINT
        sync: false 
      - key: CONTENT_SAFETY_KEY
        sync: false  
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /health
    
  - type: web
    name: content-safety-frontend
    runtime: static
    buildCommand: echo "No build needed for static HTML"
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
